language: ruby
cache:
  bundler: true
  pip: true
  directories:
  - _site
rvm:
- 2.2
install:
- pip install awscli
- bundle install
before_script:
- aws s3 sync s3://meta-dxfoto-ru _data --quiet --exclude "logs/*"
script:
- bundle exec jekyll build -I
branches:
  only:
  - deploy-aerobatic
after_success:
  - bundle exec s3_website push
#  - rm -f .gitignore && touch .gitignore
#  - git config --global user.name "Travis CI"
#  - git config --global user.email "nobody@nowhere.org"
#  - TRAVIS_COMMIT=$(git log --format=%B -n 1)
#  - git add .
#  - git commit -m "$TRAVIS_COMMIT"
#deploy:
#  provider: s3
#  bucket: www.dxfoto.ru
#  local-dir: _site
#  acl: public_read
#  region: eu-west-1
#  on:
#    repo: at8eqeq3/dxfoto.ru
#    branch: deploy-aerobatic
