language: ruby
cache: bundler
rvm:
- 2.2
script:
- bundle exec jekyll build
branches:
  only:
  - gh-pages
after_success:
  - rm -f .gitignore && touch .gitignore
deploy:
  provider: s3
  bucket: www-dxfoto-ru
  local-dir: _site
  acl: public_read
  on:
    repo: at8eqeq3/dxfoto.ru
    branch: gh-pages
