language: ruby
cache: bundler
rvm:
- 2.2
script:
- bundle exec jekyll build
branches:
  only:
  - deploy-aerobatic
after_success:
  - rm -f .gitignore && touch .gitignore
  - git config --global user.name "Travis CI"
  - git config --global user.email "nobody@nowhere.org"
  - TRAVIS_COMMIT=$(git log --format=%B -n 1)
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
deploy:
  provider: s3
  bucket: www-dxfoto-ru
  local-dir: _site
  acl: public_read
  region: eu-west-1
  on:
    repo: at8eqeq3/dxfoto.ru
    branch: gh-pages
