language: ruby
cache: bundler
rvm:
  - 2.2
script:
  - bundle exec jekyll build
branches:
  only:
    - gh-pages
after_success:
  - rm -f .gitignore
  #- echo -e \!_site > .gitignore
  - TRAVIS_COMMIT=$(git log --format=%B -n 1)
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
  - git push --force https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@$AZURE_WA_SITE.scm.azurewebsites.net:443/$AZURE_WA_SITE.git HEAD:master
#deploy:
#  skip_cleanup: true
#  provider: azure_web_apps
#  on: gh-pages
#  verbose: true
