language: ruby
cache:
  bundler: true
  pip: true
  directories:
  - _site
  - _amp
rvm:
- 2.4
install:
- pip install --user awscli
- bundle install
before_script:
- aws s3 sync s3://meta-dxfoto-ru _data --quiet --exclude "logs/*"
script:
- bundle exec jekyll build -I
- AMP=yes bundle exec jekyll build -I --config _config-amp.yml
branches:
  only:
  - deploy-aerobatic
after_success:
  - bundle exec s3_website push
  - mv -f _amp/index-amp.html _amp/index.html
  - mv -f _amp/error-amp.html _amp/error.html
  - AMP=yes bundle exec s3_website push
  - curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "X-Auth-Email: $CF_AUTH_EMAIL" -H "X-Auth-Key: $CF_API_KEY" -H "Content-Type: application/json" --data '{"files": ["https://www.dxfoto.ru/", "https://amp.dxfoto.ru/"]}'
#  - rm -f .gitignore && touch .gitignore
#  - git config --global user.name "Travis CI"
#  - git config --global user.email "nobody@nowhere.org"
#  - TRAVIS_COMMIT=$(git log --format=%B -n 1)
#  - git add .
#  - git commit -m "$TRAVIS_COMMIT"
#deploy:
#  provider: s3
#  bucket: www.dxfoto.ru
#  local-dir: _site
#  acl: public_read
#  region: eu-west-1
#  on:
#    repo: at8eqeq3/dxfoto.ru
#    branch: deploy-aerobatic
